[project]
name = "ffmpeg-python-helper"
version = "3.2.0"
description = "A Python wrapper for FFMPEG that provides a simple, intuitive API for common video processing tasks including format conversion, GIF creation, and video trimming."
readme = "README.md"
authors = [
    { name = "marjon", email = "petmalu.marjon@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ffmpeg-python-helper = "ffmpeg_python_helper:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
